### ISSUE TITLE
New build for 3.1.rc1

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pymc3-feedstock#11]
We just released v3.1.rc1, can we build new conda-forge packages?

https://github.com/pymc-devs/pymc3/releases/tag/v3.1.rc1

**Comment by ericmjl** [comment]
I'll get started on it.

**Comment by twiecki** [comment]
@ericmjl Thanks! There's also a new theano release candidate for 0.9 which we rely on.

**Comment by ericmjl** [comment]
@twiecki is 3.1rc1 on PyPI yet? If not can you get it up there? conda-forge builds rely on PyPI for downloading + MD5 hashes.

**Comment by ocefpaf** [comment]
>  conda-forge builds rely on PyPI for downloading + MD5 hashes.

Not necessarily. You can point the source to GitHub, or any other source really. PyPI is just convenient.

**Comment by ericmjl** [comment]
@ocefpaf communicated wrongly, my bad! Yes, it's more convenient to rely on PyPI than on GitHub; I remember vaguely from a conversation with another conda-forge core member that it's preferable to use PyPI than GitHub, I think?

**Comment by twiecki** [comment]
@fonnesbeck will upload it.

**Comment by ocefpaf** [comment]
> Remember vaguely from a conversation with another conda-forge core member that it's preferable to use PyPI than GitHub, I think?

That is debatable :smile: I prefer it closer to the source. Which usually means GitHub. Also, sometimes GitHub has files we need, like LICENSE files, that are absent from source tarballs. Not to mention when PyPI source tarballs introduced pre-complied stuff that we should be compiling, but that is not too common.

**Comment by ericmjl** [comment]
Ah, okay. Let me go ahead and try first with the GitHub release then.

**Comment by ocefpaf** [comment]
Here is an example:

```yaml
source:
  fn: nco-{{ version }}.tar.gz
  url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
  sha256: 1c2ab906fc81f91bf8aff3e6da27ae7a4c89821c5836d787188fff5262418062
```

**Comment by twiecki** [comment]
Thanks guys!
