### ISSUE TITLE
Update to release 3.1rc3

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pymc3-feedstock#15]
We just released 3.1rc3, can someone update? https://pypi.python.org/pypi/pymc3

**Comment by ericmjl** [comment]
@twiecki see #17, just pushed it up.

Just curious, what's the purpose of releasing RCs via conda-forge? Testing and looking for bugs in the wild?

**Comment by twiecki** [comment]
@ericmjl Mainly for catching build bugs and for making it easier for others to test it out.
