### ISSUE TITLE
Un-necessary exclusion of py2k

### ISSUE THREAD

**Issue by kpalin** [conda-forge/pymc3-feedstock#20]
Following line #16 in meta.yml unnecessarily excludes python2 users 
  skip: True  # [py2k]

Monkey-patched it and it worked on Linux  3.13.0-129-generic #178-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux  but don't know how to make a proper pull request for conda-forge recipies.

**Comment by ericmjl** [comment]
ping @twiecki @fonnesbeck - is PyMC3 going to follow Python dev's schedule for deprecating py2k support? This will inform whether it makes sense to turn off py2k builds for pymc3 or not.

If you'll be following Python's schedule, then it makes sense to keep py2k builds for now. 

If you'll be dropping py2k support soon, then it makes no sense to keep py2k builds at all.

What are your thoughts?

**Comment by twiecki** [comment]
We will in 2020, but there is no reason to exclude it right now. A PR would be much appreciated.

**Comment by ericmjl** [comment]
@kpalin: Please put in a PR removing that line, and let's see how the tests pass.
