### ISSUE TITLE
Warning about no g++ detected

### ISSUE THREAD

**Issue by maresb** [conda-forge/pymc3-feedstock#64]
In the build logs, during the tests, on `import pymc3`, I overlooked [this warning](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=333530&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=831):

```
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

**Comment by maresb** [comment]
Here's a status update.

As can be seen from [the pipeline logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=339768&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05) of [my testing branch](https://github.com/conda-forge/pymc3-feedstock/pull/66), the warning is gone for Linux and OSX but [persists in Windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=339768&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=1060).

At least in case of Windows, it suggests the name of a `conda` package to install (`m2w64-toolchain`), so I wouldn't feel so bad to let that warning remain.

Note: I don't have a Windows computer, so I can't test things myself... the best I can do is to test via the CI pipeline.

I had [a discussion with @beckermr over Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=60cf1469effd491d8c755a4f) regarding `g++` since I'm no compiler expert.

Note that this is a **runtime** warning, **not** a **build** warning. We determined for the moment that in order to solve this warning for all platforms, we probably could not keep the package noarch.

Regarding this, I have a follow-up question for @beckermr: What if instead we create a new recipe which installs `cxx-compilers` on Linux/OSX and installs `m2w64-toolchain` on Windows? Would such a package allow this recipe to stay noarch?

A final note: on OSX there seem to be a lot of [ClobberWarning](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=339768&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=784)s. I have no idea whether or not this indicates an actual problem.

**Comment by beckermr** [comment]
The noarch optimization is not worth the hassle here. I'd just use a selector and install what you need.

**Comment by maresb** [comment]
Thanks @beckermr, trying it out now...

**Comment by maresb** [comment]
@beckermr, looks like it's working now on all platforms.

I'm still not sure what to make of all these [clobber warnings](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=339806&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=784) on OSX. Are they safe to ignore???

**Comment by beckermr** [comment]
Build the package locally on OS X and then open it up and inspect the paths. As long as pymc3 isn't somehow causing them, then you can ignore them I think.

**Comment by maresb** [comment]
@beckermr I can't do that locally since I don't have OSX. I looked for build artifacts but unfortunately didn't find any.

**Comment by beckermr** [comment]
there is a key in conda-forge.yml you can set to tell aziure to save artifacts - you'll need to rerender after

```
azure:
  upload_packages: False
```

**Comment by maresb** [comment]
@beckermr that's amazing! That will be extremely helpful for me for debugging on these other platforms.

The artifacts are now available [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=339863&view=artifacts&pathAsName=false&type=publishedArtifacts). I looked through the OSX artifacts and I didn't notice anything which seemed related to the compilers, however I'm not sure exactly what I'm checking for...

Would you be able to have a quick look so we could get this approved? Thanks so much for all your help!!!!!

**Comment by beckermr** [comment]
Yep looks fine. None of the files that are clobbering are in this artifact so it must be something with cctools and the compilers.
